version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:lein-2.7.1
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout
      - restore_cache:
          keys:
            - greenlight-{{ checksum "project.clj" }}
            - greenlight-
      - run: lein deps
      - run: lein check
      - run: lein test
      - run: lein coverage --codecov
      - save_cache:
          paths:
            - ~/.m2
          key: greenlight-{{ checksum "project.clj" }}
      - store_artifacts:
          path: target/coverage
          destination: coverage
      - run:
          name: Publish Coverage
          command: "(curl -s https://codecov.io/bash > codecov) && bash codecov -f target/coverage/codecov.json"
